---
title: "Ayuda Natalia"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
#library(stringr) included in tidyr
library(tidyr)
#library(magrittr) included in tidyr
```

```{r}
# temporarily chanding working directory to read files
setwd("/Users/Nati/Desktop/QuestCoffeeRustLandscape/Outputs")
csv.dir <- "/Users/Nati/Desktop/QuestCoffeeRustLandscape/Outputs"

# Read in model outputs --------------------------------------
# Read all csv's into a list
filenames <- list.files(csv.dir, pattern = "*.csv", full.names = T)
the_names <- list.files(csv.dir, pattern = "*.csv", full.names = F)

# text extraction code from Caitlin Littlefield 
left = function(text, num_char) {
  substr(text, 1, num_char)
}

mid = function(text, start_num, num_char) {
  substr(text, start_num, start_num + num_char - 1)
}

right = function(text, num_char) {
  substr(text, nchar(text) - (num_char-1), nchar(text))
}

# make empty def list
def <- list()
disp <- list()

# 
loop.ready <- c(1:length(the_names))

for(i in loop.ready) {
  def[[i]] <- mid(the_names[[i]],4,2)
  disp[[i]] <- right(the_names[[i]],1)
  vals <- filenames[[i]][,2]

  
# code from Ollín 

token_name <- function(x){
   a <- gsub('.csv','',x)
   a
}

the_names <- c("Time") %>% append(lapply(the_names,token_name))

i = 0
for (name in filenames){
  if (i == 0){
    df <- read.csv(name,header = F)
    i = i+1
  }else{
    df_temp <- read.csv(name,header = F)
    df <- as.dataframe(cbind(df,df_temp$V2))
  }
  df
}
colnames(df) <- the_names

class(df)

head(df)
``` 